version: '3'

#Volumes for DB data
volumes:
  mongo-data:
      
#Enable Network communication   
networks:
   app-network:
       
 #images list
services:

  #Mongodb
  mongo-db:
    image: "mongo"
    container_name: mongo-db
      # persistent volume
    volumes:
      - mongo-data:/var/lib/mongo/data
    ports:
      - 27017:27017 
     #Environment variable for DB url
    environment:
      - MONGO_DATA_BASE=etf
    networks:
      - app-network

  #Back-end Spring Boot Application
  backend:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: ./backend
    container_name: backend
    #Environment variables for Spring Boot Application.
    environment:
      - MONGO_URL=mongo-db
      - MONGO_DATA_BASE=etf
      - MONGO_PORT=27017
    ports:
      - 8080:8080 
    depends_on:
      - mongo-db
    networks:
      - app-network  

  #Fron-end ReactJS Application
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - mongo-db  
    networks:
      - app-network
      



