apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  ports:
    - port: 27017           
      nodePort: 30003       
  selector:
    app: mongo
    
    
    
 #BASH
 # - minikube ip
 # - curl http://[minikube ip]:[nodePort]   
  
  
 #kubectl expose deployment app-server --name app-server-service  --type NodePort --protocol TCP --port 8080 --node-port 30001
  